flags:
  hdph-closure:
    buildtest: false
packages:
  - hdph-closure/
  - hdph/

extra-deps:
  - network-multicast-0.1.1
  - pqueue-1.3.2

# - transformers-0.5.2.0
# - transformers-compat-0.5.1.4

resolver: lts-7.3
